### ISSUE TITLE
TimeWrap or TimeWarp?

### ISSUE THREAD

**Issue by itn3000** [Nicogo1705/Stride.BepuPhysics#38]
"Settings" section in README.md says there is "TimeWrap" variable,
but BepuSettings class has "TimeWarp" variable.Which may be correct?

**Comment by Nicogo1705** [comment]
https://github.com/Nicogo1705/Stride.BepuPhysics/issues/6

Oops, we forgot to update the readme. We are moving the readme to the wiki, but since the project is still under development, the docs quickly become outdated.

**Comment by Doprez** [comment]
just updated the [Wiki](https://github.com/Nicogo1705/Stride.BepuPhysics/wiki/Configuration) now, thank you.

**Comment by Doprez** [comment]
https://github.com/Nicogo1705/Stride.BepuPhysics/pull/40 PR to remove old readme and reference the Wiki instead.
