### ISSUE TITLE
Rotating parent container with child colliders breaks orientation

### ISSUE THREAD

**Issue by Doprez** [Nicogo1705/Stride.BepuPhysics#44]
![image](https://github.com/Nicogo1705/Stride.BepuPhysics/assets/73259914/195a602e-47c9-419e-8a52-ce99ac239973)

I found a bug where when the parent entity is rotated the child offsets are wrong.

![image](https://github.com/Nicogo1705/Stride.BepuPhysics/assets/73259914/43f81eed-19c6-4b8a-b50c-89219fbe6a60)

**Comment by Nicogo1705** [comment]
As discuted with @Eideren on stride discord, we are going to change the collider system.
We should copy how stride work.
I'm already working on it. (as moving debug render to an other project, adding Stride.BepuPhysics.Soft & more)

**Comment by Nicogo1705** [comment]
Fixed
